=== api-evangelist/amazon-codebuild/json-schema/amazon-codebuild-start-build-input-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-codebuild/refs/heads/main/json-schema/amazon-codebuild-start-build-input-schema.json",
  "title": "StartBuildInput",
  "description": "StartBuildInput schema from Amazon CodeBuild",
  "type": "object",
  "properties": {
    "projectName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NonEmptyString"
        },
        {
          "description": "The name of the CodeBuild build project to start running a build."
        }
      ]
    },
    "secondarySourcesOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ProjectSources"
        },
        {
          "description": " An array of <code>ProjectSource</code> objects. "
        }
      ]
    },
    "secondarySourcesVersionOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ProjectSecondarySourceVersions"
        },
        {
          "description": " An array of <code>ProjectSourceVersion</code> objects that specify one or more versions of the project's secondary sources to be used for this build only. "
        }
      ]
    },
    "sourceVersion": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "<p>The version of the build input to be built, for this build only. If not specified, the latest version is used. If specified, the contents depends on the source provider:</p> <dl> <dt>CodeCommit</dt> <dd> <p>The commit ID, branch, or Git tag to use.</p> </dd> <dt>GitHub</dt> <dd> <p>The commit ID, pull request ID, branch name, or tag name that corresponds to the version of the source code you want to build. If a pull request ID is specified, it must use the format <code>pr/pull-request-ID</code> (for example <code>pr/25</code>). If a branch name is specified, the branch's HEAD commit ID is used. If not specified, the default branch's HEAD commit ID is used.</p> </dd> <dt>Bitbucket</dt> <dd> <p>The commit ID, branch name, or tag name that corresponds to the version of the source code you want to build. If a branch name is specified, the branch's HEAD commit ID is used. If not specified, the default branch's HEAD commit ID is used.</p> </dd> <dt>Amazon S3</dt> <dd> <p>The version ID of the object that represents the build input ZIP file to use.</p> </dd> </dl> <p>If <code>sourceVersion</code> is specified at the project level, then this <code>sourceVersion</code> (at the build level) takes precedence. </p> <p>For more information, see <a href=\"https://docs.aws.amazon.com/codebuild/latest/userguide/sample-source-version.html\">Source Version Sample with CodeBuild</a> in the <i>CodeBuild User Guide</i>. </p>"
        }
      ]
    },
    "artifactsOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ProjectArtifacts"
        },
        {
          "description": "Build output artifact settings that override, for this build only, the latest ones already defined in the build project."
        }
      ]
    },
    "secondaryArtifactsOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ProjectArtifactsList"
        },
        {
          "description": " An array of <code>ProjectArtifacts</code> objects. "
        }
      ]
    },
    "environmentVariablesOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/EnvironmentVariables"
        },
        {
          "description": "A set of environment variables that overrides, for this build only, the latest ones already defined in the build project."
        }
      ]
    },
    "sourceTypeOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SourceType"
        },
        {
          "description": "A source input type, for this build, that overrides the source input defined in the build project."
        }
      ]
    },
    "sourceLocationOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "A location that overrides, for this build, the source location for the one defined in the build project."
        }
      ]
    },
    "sourceAuthOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SourceAuth"
        },
        {
          "description": "An authorization type for this build that overrides the one defined in the build project. This override applies only if the build project's source is BitBucket or GitHub."
        }
      ]
    },
    "gitCloneDepthOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/GitCloneDepth"
        },
        {
          "description": "The user-defined depth of history, with a minimum value of 0, that overrides, for this build only, any previous depth of history defined in the build project."
        }
      ]
    },
    "gitSubmodulesConfigOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/GitSubmodulesConfig"
        },
        {
          "description": " Information about the Git submodules configuration for this build of an CodeBuild build project. "
        }
      ]
    },
    "buildspecOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "<p>A buildspec file declaration that overrides, for this build only, the latest one already defined in the build project.</p> <p> If this value is set, it can be either an inline buildspec definition, the path to an alternate buildspec file relative to the value of the built-in <code>CODEBUILD_SRC_DIR</code> environment variable, or the path to an S3 bucket. The bucket must be in the same Amazon Web Services Region as the build project. Specify the buildspec file using its ARN (for example, <code>arn:aws:s3:::my-codebuild-sample2/buildspec.yml</code>). If this value is not provided or is set to an empty string, the source code must contain a buildspec file in its root directory. For more information, see <a href=\"https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-name-storage\">Buildspec File Name and Storage Location</a>. </p>"
        }
      ]
    },
    "insecureSslOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/WrapperBoolean"
        },
        {
          "description": "Enable this flag to override the insecure SSL setting that is specified in the build project. The insecure SSL setting determines whether to ignore SSL warnings while connecting to the project source code. This override applies only if the build's source is GitHub Enterprise."
        }
      ]
    },
    "reportBuildStatusOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/WrapperBoolean"
        },
        {
          "description": "<p> Set to true to report to your source provider the status of a build's start and completion. If you use this option with a source provider other than GitHub, GitHub Enterprise, or Bitbucket, an <code>invalidInputException</code> is thrown. </p> <p>To be able to report the build status to the source provider, the user associated with the source provider must have write access to the repo. If the user does not have write access, the build status cannot be updated. For more information, see <a href=\"https://docs.aws.amazon.com/codebuild/latest/userguide/access-tokens.html\">Source provider access</a> in the <i>CodeBuild User Guide</i>.</p> <note> <p> The status of a build triggered by a webhook is always reported to your source provider. </p> </note>"
        }
      ]
    },
    "buildStatusConfigOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/BuildStatusConfig"
        },
        {
          "description": "Contains information that defines how the build project reports the build status to the source provider. This option is only used when the source provider is <code>GITHUB</code>, <code>GITHUB_ENTERPRISE</code>, or <code>BITBUCKET</code>."
        }
      ]
    },
    "environmentTypeOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/EnvironmentType"
        },
        {
          "description": "A container type for this build that overrides the one specified in the build project."
        }
      ]
    },
    "imageOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NonEmptyString"
        },
        {
          "description": "The name of an image for this build that overrides the one specified in the build project."
        }
      ]
    },
    "computeTypeOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ComputeType"
        },
        {
          "description": "The name of a compute type for this build that overrides the one specified in the build project."
        }
      ]
    },
    "certificateOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The name of a certificate for this build that overrides the one specified in the build project."
        }
      ]
    },
    "cacheOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ProjectCache"
        },
        {
          "description": "A ProjectCache object specified for this build that overrides the one defined in the build project."
        }
      ]
    },
    "serviceRoleOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NonEmptyString"
        },
        {
          "description": "The name of a service role for this build that overrides the one specified in the build project."
        }
      ]
    },
    "privilegedModeOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/WrapperBoolean"
        },
        {
          "description": "Enable this flag to override privileged mode in the build project."
        }
      ]
    },
    "timeoutInMinutesOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TimeOut"
        },
        {
          "description": "The number of build timeout minutes, from 5 to 480 (8 hours), that overrides, for this build only, the latest setting already defined in the build project."
        }
      ]
    },
    "queuedTimeoutInMinutesOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TimeOut"
        },
        {
          "description": " The number of minutes a build is allowed to be queued before it times out. "
        }
      ]
    },
    "encryptionKeyOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NonEmptyString"
        },
        {
          "description": "<p>The Key Management Service customer master key (CMK) that overrides the one specified in the build project. The CMK key encrypts the build output artifacts.</p> <note> <p> You can use a cross-account KMS key to encrypt the build output artifacts if your service role has permission to that key. </p> </note> <p>You can specify either the Amazon Resource Name (ARN) of the CMK or, if available, the CMK's alias (using the format <code>alias/&lt;alias-name&gt;</code>).</p>"
        }
      ]
    },
    "logsConfigOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LogsConfig"
        },
        {
          "description": " Log settings for this build that override the log settings defined in the build project. "
        }
      ]
    },
    "registryCredentialOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/RegistryCredential"
        },
        {
          "description": " The credentials for access to a private registry. "
        }
      ]
    },
    "imagePullCredentialsTypeOverride": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ImagePullCredentialsType"
        },
        {
          "description": "<p>The type of credentials CodeBuild uses to pull images in your build. There are two valid values: </p> <dl> <dt>CODEBUILD</dt> <dd> <p>Specifies that CodeBuild uses its own credentials. This requires that you modify your ECR repository policy to trust CodeBuild's service principal.</p> </dd> <dt>SERVICE_ROLE</dt> <dd> <p>Specifies that CodeBuild uses your build project's service role. </p> </dd> </dl> <p>When using a cross-account or private registry image, you must use <code>SERVICE_ROLE</code> credentials. When using an CodeBuild curated image, you must use <code>CODEBUILD</code> credentials. </p>"
        }
      ]
    },
    "debugSessionEnabled": {
      "allOf": [
        {
          "$ref": "#/components/schemas/WrapperBoolean"
        },
        {
          "description": "Specifies if session debugging is enabled for this build. For more information, see <a href=\"https://docs.aws.amazon.com/codebuild/latest/userguide/session-manager.html\">Viewing a running build in Session Manager</a>."
        }
      ]
    }
  },
  "required": [
    "projectName"
  ]
}

=== api-evangelist/amazon-codebuild/examples/amazon-codebuild-start-build-batch-input-example.json
{
  "projectName": "example-resource",
  "secondarySourcesOverride": "500123",
  "secondarySourcesVersionOverride": "500123",
  "sourceVersion": "1.0.0",
  "artifactsOverride": "500123",
  "secondaryArtifactsOverride": "500123",
  "environmentVariablesOverride": "500123",
  "sourceTypeOverride": "500123"
}
