=== api-evangelist/amazon-codebuild/json-schema/amazon-codebuild-report-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-codebuild/refs/heads/main/json-schema/amazon-codebuild-report-schema.json",
  "title": "Report",
  "description": "Information about the results from running a series of test cases during the run of a build project. The test cases are specified in the buildspec for the build project using one or more paths to the test case files. You can specify any type of tests you want, such as unit tests, integration tests, and functional tests. ",
  "type": "object",
  "properties": {
    "arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NonEmptyString"
        },
        {
          "description": " The ARN of the report run. "
        }
      ]
    },
    "type": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ReportType"
        },
        {
          "description": "<p>The type of the report that was run.</p> <dl> <dt>CODE_COVERAGE</dt> <dd> <p>A code coverage report.</p> </dd> <dt>TEST</dt> <dd> <p>A test report.</p> </dd> </dl>"
        }
      ]
    },
    "name": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": " The name of the report that was run. "
        }
      ]
    },
    "reportGroupArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NonEmptyString"
        },
        {
          "description": " The ARN of the report group associated with this report. "
        }
      ]
    },
    "executionId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": " The ARN of the build run that generated this report. "
        }
      ]
    },
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ReportStatusType"
        },
        {
          "description": " The status of this report. "
        }
      ]
    },
    "created": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Timestamp"
        },
        {
          "description": " The date and time this report run occurred. "
        }
      ]
    },
    "expired": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Timestamp"
        },
        {
          "description": " The date and time a report expires. A report expires 30 days after it is created. An expired report is not available to view in CodeBuild. "
        }
      ]
    },
    "exportConfig": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ReportExportConfig"
        },
        {
          "description": " Information about where the raw data used to generate this report was exported. "
        }
      ]
    },
    "truncated": {
      "allOf": [
        {
          "$ref": "#/components/schemas/WrapperBoolean"
        },
        {
          "description": " A boolean that specifies if this report run is truncated. The list of test cases is truncated after the maximum number of test cases is reached. "
        }
      ]
    },
    "testSummary": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TestReportSummary"
        },
        {
          "description": " A <code>TestReportSummary</code> object that contains information about this test report. "
        }
      ]
    },
    "codeCoverageSummary": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CodeCoverageReportSummary"
        },
        {
          "description": "A <code>CodeCoverageReportSummary</code> object that contains a code coverage summary for this report."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-codebuild/examples/amazon-codebuild-report-example.json
{
  "arn": "arn:aws:service:us-east-1:123456789012:resource/example",
  "type": "STANDARD",
  "name": "example-resource",
  "reportGroupArn": "arn:aws:service:us-east-1:123456789012:resource/example",
  "executionId": "500123",
  "status": "ACTIVE",
  "created": "example-value",
  "expired": "example-value"
}
